### PR TITLE
added fedora

### PR DESCRIPTION
**Pull request by lweller**
I'm sussessfully using this module on fedora.

### CODE REVIEW

**Comment by lweller** [comment]
@ethanhs : would be really nice if this PR could be merged into master and a new release get deployt on forge.puppet.com

**Review by emmatyping — APPROVED** [review]
Thanks, sorry this seems to have slipped through the cracks.

**Comment by emmatyping** [comment]
I'll try to publish this tomorrow at some point.

**Comment by lweller** [comment]
@ethanhs thx a lot

**Comment by lweller** [comment]
It would be very nice, if you can release the current version on forge.puppet.com so that we are able to reference an official version again. Thanks a lot.

**Comment by emmatyping** [comment]
https://forge.puppet.com/modules/ethanhs/snapd/1.4.0

Done! Hopefully the versions of Fedora I listed are fine, if not I can push another update.

**Pull request merged**
